# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Qt file/neko_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from qfluentwidgets import ComboBox, LineEdit, PlainTextEdit, PushButton
from qfluentwidgets.multimedia import VideoWidget
from PyQt5.QtCore import QUrl
from qfluentwidgets import ToolButton, FluentIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 750)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        
        
        # PlainTextEdit widget
        self.PlainTextEdit = PlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlainTextEdit.sizePolicy().hasHeightForWidth())
        self.PlainTextEdit.setSizePolicy(sizePolicy)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.verticalLayout_2.addWidget(self.PlainTextEdit)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # LineEdit widget
        self.LineEdit = LineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit.sizePolicy().hasHeightForWidth())
        self.LineEdit.setSizePolicy(sizePolicy)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        
        # ToolButton widget
        self.ToolButton = ToolButton(FluentIcon.SEND.icon(FluentIcon.SEND))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolButton.sizePolicy().hasHeightForWidth())
        self.ToolButton.setSizePolicy(sizePolicy)
        self.ToolButton.setIconSize(QtCore.QSize(15, 15))
        self.ToolButton.setObjectName("ToolButton")
        self.horizontalLayout.addWidget(self.ToolButton)
        
        
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        # ComboBox_2 widget
        self.comboBox_2 = ComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("ComboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        
        # ComboBox widget
        self.comboBox_1 = ComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        self.comboBox_1.setObjectName("ComboBox_1")
        self.horizontalLayout_2.addWidget(self.comboBox_1)
        
        # PushButton widget
        self.PushButton = PushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton.sizePolicy().hasHeightForWidth())
        self.PushButton.setSizePolicy(sizePolicy)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_2.addWidget(self.PushButton)
        
        # PushButton_2 widget
        self.PushButton_2 = PushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_2.sizePolicy().hasHeightForWidth())
        self.PushButton_2.setSizePolicy(sizePolicy)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        #videoWidget
        self.videoWidget = VideoWidget(self.centralwidget)
        self.videoWidget.setVideo(QUrl.fromLocalFile("D:\\Qt file\\test_4\\test.mp4"))
        self.verticalLayout_4.addWidget(self.videoWidget)  # 添加到 verticalLayout_4
        self.videoWidget.play()

        
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "谁家白菜？"))   #第二个框框改窗口标题
        self.PlainTextEdit.setPlainText(_translate("MainWindow", "布什戈门"))
        
        #combox组件
        self.comboBox_1.setText(_translate("MainWindow", "形象替换"))
        image_items=['自定义形象','真白花音','永雏塔菲']
        self.comboBox_1.addItems(image_items)
        self.comboBox_1.setPlaceholderText("形象替换")
        self.comboBox_1.setCurrentIndex(-1)
        self.comboBox_1.currentIndexChanged.connect(lambda image_index: print(self.comboBox_1.currentText()))
        #信号，将括号内的lanbda表达式换成一个函数

        self.comboBox_2.setText(_translate("MainWindow", "音色替换"))
        voice_items=['自定义音色','真白花音','永雏塔菲']
        self.comboBox_2.addItems(voice_items)
        self.comboBox_2.setPlaceholderText("音色替换")
        self.comboBox_2.setCurrentIndex(-1)
        self.comboBox_2.currentIndexChanged.connect(lambda voice_index: print(self.comboBox_2.currentText()))
        #信号，将括号内的lanbda表达式换成一个函数

        #button组件
        self.PushButton.setText(_translate("MainWindow", "新建形象"))
        


        self.PushButton_2.setText(_translate("MainWindow", "新建音色"))



